//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apollo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apollo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ApolloCover_jpg {
            get {
                object obj = ResourceManager.GetObject("ApolloCover_jpg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ApolloCoverFooter_png {
            get {
                object obj = ResourceManager.GetObject("ApolloCoverFooter_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ApolloCoverHeader_png {
            get {
                object obj = ResourceManager.GetObject("ApolloCoverHeader_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///body {
        ///  margin: 0px;
        ///  padding: 0px;
        ///  font-family: Arial, Garamond, Sans-Serif;
        ///}
        ///
        ///#course_title {
        ///  border: 1px black solid;
        ///  font-size: 1.2em;
        ///  padding:4px;
        ///  color: Black;
        ///  margin-bottom: 0px;
        ///}
        ///
        ///#course_subtitle {
        ///  margin-top: 0px;
        ///  padding: 2px;
        ///  padding-left: 4px;
        ///  margin-bottom: 10;
        ///  font-size: 0.7em;
        ///  color: #eee;
        ///  background-color: Black;
        ///  font-family: Arial Black;
        ///}
        ///
        ///#course_table, #course_table td {
        /// border: 1px solid black;
        ///  border-collapse: collapse;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CptCourseDescription_css {
            get {
                return ResourceManager.GetString("CptCourseDescription_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;xsl:stylesheet
        ///  version=&quot;1.0&quot;
        ///  xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///  xmlns:cd=&quot;http://www.criticalpathtraining.com/schema/coursedescription/1.0&quot;&gt;
        ///
        ///  &lt;xsl:output method=&quot;html&quot; indent=&quot;yes&quot; doctype-public=&quot;html&quot; /&gt;
        ///
        ///  &lt;xsl:template match=&quot;/cd:CourseDescription&quot;&gt;
        ///
        ///    &lt;html&gt;
        ///
        ///      &lt;head&gt;
        ///        &lt;title&gt;
        ///          &lt;xsl:value-of select=&quot;cd:CourseCode&quot;/&gt;: &lt;xsl:value-of select=&quot;cd:CourseTitle&quot;/&gt;
        ///        &lt;/title&gt;
        ///        &lt;link rel=&quot;stylesheet [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CptCourseDescription_xsl {
            get {
                return ResourceManager.GetString("CptCourseDescription_xsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CptCourseDescriptionHeader_png {
            get {
                object obj = ResourceManager.GetObject("CptCourseDescriptionHeader_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CptCourseManual_dotx {
            get {
                object obj = ResourceManager.GetObject("CptCourseManual_dotx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CptSellsheet_dotx {
            get {
                object obj = ResourceManager.GetObject("CptSellsheet_dotx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complying with all applicable copyright laws is the responsibility of the user. All rights reserved. Without limiting the rights under copyright, no part of this document may be reproduced, stored in or introduced into a retrieval system, or transmitted in any form or by any means (electronic, mechanical, photocopying, recording, or otherwise), or for any purpose, without express written permission of Critical Path Training, LLC..
        /// </summary>
        internal static string LegalBody1 {
            get {
                return ResourceManager.GetString("LegalBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed and bound in Canada..
        /// </summary>
        internal static string LegalBody2 {
            get {
                return ResourceManager.GetString("LegalBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft, Microsoft Press, ActiveX, Excel, FrontPage, Internet Explorer, PowerPoint, SharePoint, Webdings, Windows, and Windows 7 are either registered trademarks or trademarks of Microsoft Corporation in the United States and/or other countries. Other product and company names mentioned herein may be the trademarks of their respective owners..
        /// </summary>
        internal static string LegalBody3 {
            get {
                return ResourceManager.GetString("LegalBody3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unless otherwise noted, the example companies, organizations, products, domain names, e-mail addresses, logos, people, places, and events depicted herein are fictitious, and no association with any real company, organization, product, domain name, e-mail address, logo, person, place, or event is intended or should be inferred..
        /// </summary>
        internal static string LegalBody4 {
            get {
                return ResourceManager.GetString("LegalBody4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SectionHeaderImage_gif {
            get {
                object obj = ResourceManager.GetObject("SectionHeaderImage_gif", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TitleHeaderImage_gif {
            get {
                object obj = ResourceManager.GetObject("TitleHeaderImage_gif", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
